spring.application.name=demo

spring.datasource.url=jdbc:postgresql://localhost:5432/testrag
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.chat.options.model=llama3.2:latest
spring.ai.ollama.embedding.options.model=nomic-embed-text:latest

spring.ai.vectorstore.pgvector.initialize-schema=true


app.pdf.chunk-size=500
app.pdf.chunk-overlap=100



